import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Sparkles, CheckCircle2, ArrowRight, FileText, Sliders, Eye, Building2 } from 'lucide-react';
import ScoreGauge from '../components/common/ScoreGauge';
import { getRecommendations } from '../services/api';

export default function RecommendationsPage() {
  const navigate = useNavigate();
  const [recommendations, setRecommendations] = useState([]);

  useEffect(() => {
    async function load() {
      const data = await getRecommendations();
      setRecommendations(data);
    }
    load();
  }, []);

  return (
    <div className="space-y-8 pb-12">
      {/* Header */}
      <div>
        <div className="flex items-center gap-2 text-xs font-semibold text-purple-400">
          <Sparkles className="w-3.5 h-3.5" />
          <span>AI Intervention Design Engine</span>
        </div>
        <h1 className="text-3xl font-black text-white">AI Project Recommendations</h1>
        <p className="text-xs text-slate-400">Evidence-based capital project proposals generated by synthesizing citizen demand signals with spatial infrastructure deficits.</p>
      </div>

      {/* Recommendations Cards */}
      <div className="space-y-6">
        {recommendations.map((rec) => (
          <div key={rec.id} className="glass-panel-glow p-6 rounded-2xl border border-purple-500/30 space-y-6">
            <div className="flex flex-wrap items-start justify-between gap-4 border-b border-purple-500/20 pb-4">
              <div className="space-y-1">
                <div className="flex items-center gap-2">
                  <span className="text-[10px] font-extrabold px-2 py-0.5 rounded bg-purple-500/20 text-purple-300 border border-purple-500/30">
                    {rec.id}
                  </span>
                  <span className="text-xs text-slate-400 font-bold">{rec.region}, {rec.country}</span>
                  <span className="text-xs text-cyan-400 font-bold">• {rec.category}</span>
                </div>
                <h2 className="text-xl font-extrabold text-white">{rec.title}</h2>
              </div>
              <div className="flex items-center gap-4">
                <div className="text-right">
                  <span className="text-[10px] uppercase font-bold text-slate-400 block">Est. Investment</span>
                  <span className="text-base font-black text-cyan-300">{rec.estimatedCost}</span>
                </div>
                <ScoreGauge score={rec.priorityScore} size={70} strokeWidth={6} title="" />
              </div>
            </div>

            {/* Content Details */}
            <div className="grid md:grid-cols-2 gap-6 text-xs">
              <div className="space-y-3">
                <div className="p-3.5 rounded-xl bg-[#07111F] border border-slate-800 space-y-1">
                  <span className="text-[10px] uppercase font-bold text-slate-400">Problem Statement</span>
                  <p className="text-slate-200 leading-relaxed">{rec.problemStatement}</p>
                </div>

                <div className="p-3.5 rounded-xl bg-[#07111F] border border-slate-800 space-y-2">
                  <span className="text-[10px] uppercase font-bold text-cyan-400">Proposed Engineering Interventions</span>
                  <ul className="space-y-1 text-slate-300">
                    {rec.proposedInterventions?.map((item, idx) => (
                      <li key={idx} className="flex items-start gap-2">
                        <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 mt-1.5 shrink-0"></span>
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              <div className="space-y-3">
                <div className="p-3.5 rounded-xl bg-[#07111F] border border-slate-800 space-y-2">
                  <span className="text-[10px] uppercase font-bold text-emerald-400">Projected Outcome & Impact</span>
                  <div className="grid grid-cols-2 gap-2">
                    <div className="p-2 rounded bg-slate-900 border border-slate-800">
                      <span className="text-[9px] text-slate-500 uppercase font-bold block">Beneficiaries</span>
                      <span className="font-bold text-slate-200">{rec.expectedImpact?.beneficiaries}</span>
                    </div>
                    <div className="p-2 rounded bg-slate-900 border border-slate-800">
                      <span className="text-[9px] text-slate-500 uppercase font-bold block">Signal Reduction</span>
                      <span className="font-bold text-emerald-400">{rec.expectedImpact?.complaintReduction}</span>
                    </div>
                  </div>
                  <p className="text-[11px] text-cyan-300 font-semibold pt-1">{rec.expectedImpact?.coverageGain}</p>
                </div>

                <div className="p-3.5 rounded-xl bg-purple-950/40 border border-purple-500/30 space-y-1">
                  <span className="text-[10px] uppercase font-bold text-purple-400">AI Priority Rationale</span>
                  <p className="text-slate-300 italic leading-relaxed">"{rec.aiReasoning}"</p>
                </div>
              </div>
            </div>

            {/* Quick Action Buttons */}
            <div className="flex flex-wrap items-center justify-between gap-3 pt-3 border-t border-purple-500/20">
              <span className="text-xs text-slate-400">Status: <strong className="text-emerald-400">{rec.status}</strong></span>
              <div className="flex items-center gap-3">
                <button
                  onClick={() => navigate('/hotspots')}
                  className="px-3.5 py-2 rounded-xl text-xs font-bold bg-slate-800 text-slate-200 border border-slate-700 hover:bg-slate-700 flex items-center gap-1.5"
                >
                  <Eye className="w-3.5 h-3.5" />
                  <span>View Evidence</span>
                </button>
                <button
                  onClick={() => navigate('/policy-brief')}
                  className="px-3.5 py-2 rounded-xl text-xs font-bold bg-purple-900/60 text-purple-200 border border-purple-500/40 hover:bg-purple-800 flex items-center gap-1.5"
                >
                  <FileText className="w-3.5 h-3.5" />
                  <span>Generate Policy Brief</span>
                </button>
                <button
                  onClick={() => navigate('/impact')}
                  className="px-4 py-2 rounded-xl text-xs font-extrabold bg-gradient-to-r from-cyan-500 to-blue-600 text-white shadow-lg shadow-cyan-500/20 hover:scale-105 transition-all flex items-center gap-1.5"
                >
                  <Sliders className="w-3.5 h-3.5" />
                  <span>Simulate Impact</span>
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
